# Generated by Django 3.0.7 on 2020-07-08 04:46

from django.db import migrations
import subroutines.users.models.users


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', subroutines.users.models.users.UserManager()),
            ],
        ),
    ]
